### ISSUE TITLE
이거 뭐죠??

### ISSUE THREAD

**Issue by snack655** [codingbotPark/studying-android#1]
아니 안드로이드 한다고 그렇게 뭐라 하더니만 이래도 되는 겁니까??
레포 삭제해 주세요..;;

**Comment by codingbotPark** [comment]
안드 별거 없던데요, 그냥 mui 가 다해주더만 이참에 그냥 코딩도 GPT한테 ㄱㄱ

**Comment by snack655** [comment]
어제부터 궁금했는데 MUI가 뭐죠..
